### ISSUE TITLE
Check if all UDAs are passed with provisioning settings

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm-app-shell#10]
All provided custom attributes (UDAs) have to be available to all scripts. Few exceptions may be done, if reasoned for instance by technical irrelevance or security aspects.

**Comment by kowalczyka** [comment]
All UDAs are passed within provisioning settings. Added logging of incomin provisiong settings with https://github.com/servicecatalog/oscm-app-shell/commit/1f0dc1e0b5535e4e0fd01066c8ed6a8b2bff6d26
