### ISSUE TITLE
Access info returned from the provisioning script

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm-app-shell#11]
Provide access info returned from the provisioning script(s). 
See APP API
``` 
org.oscm.app.v2_0.data.InstanceStatus#setAccessInfo()
```

**Comment by GoebelL** [comment]
Pass access info as returned from provisioning scripts.

**Comment by kowalczyka** [comment]
What exactly shoud be put as access info? This is a string value. What should it consist of?

**Comment by uhu133** [comment]
The access info is a string optionally containing a URL. The URL can be a link to a console or an application.

**Comment by GoebelL** [comment]
@kowalczyka 
See javadoc of mentioned method. The access info is a String that is limitted to 4096 bytes. It's
semantic is depending on the type of cloud. Thus, the controller should validate the length, not more.
