### ISSUE TITLE
Collect billable events 

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm-app-shell#15]
The shell connector shall provide an additional script. This script is called regularly to collect billable events (similar to OpenStack connector).
Note: The framework is provided in APP through [org.oscm.app.v2_0.intf. APPlatformController#gatherUsageData](https://github.com/servicecatalog/oscm/blob/master/oscm-app-extsvc-2-0/javasrc/org/oscm/app/v2_0/intf/APPlatformController.java#L469)

```
boolean gatherUsageData(String controllerId, String instanceId, String startTime, String endTime, ProvisioningSettings settings)
```
This shell controller needs to implement this interface and callback BES to register the events. Same as in the OpenStack controller.

**Comment by GoebelL** [comment]
Hi @kowalczyka 
Please share a sample of the usage script in main/resources/sample that contains time parameters and some json data like valid.json.

**Comment by kowalczyka** [comment]
Sample script was added here: https://github.com/servicecatalog/oscm-app-shell/blob/master/src/main/resources/sample_scripts/sample_ok_usage_data.sh

As for time parameters, these are added to the script automatically (the same as parameters, custom attributes) and are available by default in the usage script as: START_TIME and END_TIME

**Comment by GoebelL** [comment]
@gertipoppel 
Please add this for documentation.

**Comment by GoebelL** [comment]
The description can be found in https://github.com/servicecatalog/documentation/blob/master/Development/oscm-app-shell/doc/en/ShellIntegration.pdf.
