### ISSUE TITLE
Add shell adapter to docker build

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm-app-shell#2]

**Comment by Crystalzord** [comment]
I have created separate branches for this issue: 
 - shell_adapter branch in jenkinsScripts repository on GitLab
 - shell_adapter branch in oscm-dockerbuild repository on GitHub

Right now the shell adapter is added to the docker build correctly.
I am working on few last issues connected with this task:
1. Reduce complexity of maven image Dockerfile.
2. Ensure that a jenkins job can run multiple times without additional steps.
3. Make oscm-app-shell create war archive name with pre-defined name to avoid problems in the future or find a different way to dynamically pass the shell*.war to COPY docker commands.

**Comment by Crystalzord** [comment]
http://10.140.19.25/fujitsu-bss/jenkinsScripts/merge_requests/3
https://github.com/servicecatalog/oscm-dockerbuild/pull/144
https://github.com/servicecatalog/oscm-app-shell/pull/21
