### ISSUE TITLE
Script validation Regex failing for printf with data

### ISSUE THREAD

**Issue by fabiorauber** [servicecatalog/oscm-app-shell#40]
Script RegEx validation is failing for a script containing a printf which returns a JSON with data. Inspecting the code, I see there is no comma after the double quotes between "message" and "data":

https://github.com/servicecatalog/oscm-app-shell/blob/845acc1d225c14acfebf3ec6f21535ae5f8a4cd0/src/main/java/org/oscm/app/shell/business/ScriptValidator.java#L152

**Comment by GoebelL** [comment]
Hi @fabiorauber 
thanks for the notice.
 
@Crystalzord, please check this.

**Comment by fabiorauber** [comment]
Thinking about the problem, do you think that it is necessary to validate the code of the script beforehand? I'm stating this because there are many ways to generate the correct JSON that might not pass the specified RegEx. IMHO, it would be best to validate only the output of the script.

**Comment by GoebelL** [comment]
@Crystalzord 
I agree with @fabiorauber. Prevalidating content will tie up things too much. Nice to have scripts fail fast, but preventing deligation and duplicating business logic is not the price I'd like to pay.
Let's stay with the defined JSON format, but drop the regex code. Just parse the response on the fly and care for propper error handling .

**Comment by Crystalzord** [comment]
JSON validation before script execution has been removed, therefore I close the issue.
