### ISSUE TITLE
Get Organization and user attributes within provisioning script

### ISSUE THREAD

**Issue by fabiorauber** [servicecatalog/oscm-app-shell#41]
I'm trying (and failing) to discover a way to get the User and Organization attributes (such as email, website, address, etc) within the provisioning shell script, to be used to configure the service being provisioned. Is it possible?

**Comment by GoebelL** [comment]
Well, OSCM is not going expose user's profiles nor their organization data. On the other hand, if there is some need to share certain data with the service subscription, the user is free to use, for example, custom attributes (UDAs). These attributes are transmitted by the controller same as service parameters. Means those values can be provided by customers and used within the shell scripts.

**Comment by GoebelL** [comment]
Hi @fabiorauber 
Custom attributes are meant to provide additional information that can be shared through services. As service manager you can define custom attributes for your customers and subscriptions. This is useful, for instance if the service usage requires addition information from the customer users, such as credentials to connect an external service or cloud API. In the OSCM admin portal and select **Account > manage custom attributes** from the menu. Customers can manage the attributes in their profile in the marketplace portal in **Account > Profile > Customer Attributes**.

Find details in online help ('?' link) and in [Supplier' Guide](https://github.com/servicecatalog/documentation/blob/master/Development/oscm-doc-user/resources/manuals/integration/en/Supplier.pdf), chapter 4.3.

**Comment by fabiorauber** [comment]
Hi @GoebelL,

Thanks for the answer. I tried to use the custom customer attributes, but they are not passed on to the provisioning script. Only the subscription custom attributes are. For instance, I created a custom attribute "customerDomain", and defined it for a specific customer. Then, when launching a Shell service, the following variables are being passed on to the provisioning script, as can be seen on the app-shell.log:

```
APP_BSS_USER_PWD="apassword"
APP_CONTROLLER_ID="ess.shell"
ASSIGN_USER_SCRIPT="assignuser_pm3.sh"
CHECK_STATUS_SCRIPT="status_pm3.sh"
DEASSIGN_USER_SCRIPT="deassignuser_pm3.sh"
DEPROVISIONING_SCRIPT="remove_pm3.sh"
INSTANCE_ID="367d3a2a-7d5d-4f4c-8452-b13475f58709"
NAMED_USER="1"
PERIOD="0"
PROVISIONING_SCRIPT="create_pm3.sh"
REFERENCE_ID=""
REQUESTING_ORGANIZATION_ID="f386a9f7"
REQUESTING_USER_ID="contato"
SCRIPT_FILE="create_pm3.sh"
SCRIPT_TIMEOUT_SECONDS="900"
SM_STATE="BEGIN"
SM_STATE_HISTORY=""
SM_STATE_MACHINE="provision.xml"
SUBSCRIPTION_ID="Portal Modelo"
UPDATE_SCRIPT="update_pm3.sh"
```

Note that my new custom customer attribute is not present.

**Comment by GoebelL** [comment]
@kowalczyka 
Could check this? Aren't organization attributes copied with the provisioning settings?

**Comment by kowalczyka** [comment]
Hello,

as for organization related attributes only organization id and organization name are passed to provisioning settings. Only organization id is now passed to the shell script.

As for custom attributes I can confirm that currently only those related to subscription are passed to the script (custom attributes for customer are not passed to the shell script). Both types are accessible in provisioning settings so it would really small effort to add the other type of custom attributes to be available inside script.

**Comment by GoebelL** [comment]
Ok, lets keep that on the list.
https://github.com/servicecatalog/oscm/issues/200

**Comment by kowalczyka** [comment]
Custom attributes for customer are now available in the script. Additionally organization name is also passed.

Closing the issue.
