### ISSUE TITLE
status script works not correct

### ISSUE THREAD

**Issue by elfriedegoetz** [servicecatalog/oscm-app-shell#47]
A subscription is createted ( with Status Tab) and an user is assigned
step1: click on My Subscription
step2: click Tab Status  -> works fine
step3: click Details and execute an Operation -> works fine
step4: click Tab Status
[observed]
the status script will not be executed
[expect]
the status script will  be executed again

**Comment by Crystalzord** [comment]
I confirm that this situation exists. I will look into this.

**Comment by elfriedegoetz** [comment]
works fine
