### ISSUE TITLE
Provide the possibity to execute shell/bash scripts

### ISSUE THREAD

**Issue by kowalczyka** [servicecatalog/oscm-app-shell#5]
As the repo's source is the Powershell adapter, it must be adapted to execute shell/bash scripts instead of powershell scripts

**Comment by GoebelL** [comment]
Define scripts according APP interfaces. 
E.g. see https://github.com/servicecatalog/oscm-app-shell/blob/master/src/main/java/org/oscm/app/shell/ShellController.java#L134
