### ISSUE TITLE
access info provided by provisionig but not visible in "my subscriptions"

### ISSUE THREAD

**Issue by uhu133** [servicecatalog/oscm-app-shell#57]
I am providing an access info in my provisioning script with content "hello". 
But the view in my subscrictiptions  shows the value which was defined in the technical service.

echo '{
    "status": "ok",
      "message": "Docker provisioned successfully.",
        "data": {
            "access info": "hello"
              }
      }'

echo "END_OF_SCRIPT"

**Comment by kowalczyka** [comment]
To get this done, please use "accessInfo" field instead of "access info"

**Comment by uhu133** [comment]
ok - this helped

**Comment by gertipoppel** [comment]
This is already corrected in the documentation
