### ISSUE TITLE
Keep sample files together

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm-app-shell#60]
1. Move existing [sample scripts](https://github.com/servicecatalog/oscm-app-shell/tree/master/src/test/resources/sample_scripts/advanced_scripts) to [/src/main/resources](https://github.com/servicecatalog/oscm-app-shell/tree/master/src/main/resources). 

2. Assign to @gertipoppel for documentation

**Comment by gertipoppel** [comment]
The doc has been updated accordingly
