### ISSUE TITLE
Switch organization for shell adapter

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm-app-shell#63]
The responsible provider for each adapter can be set in the APP UI.  The shell adapter needs an interface for setting the technology manager credentials of the provider. At least it must be possible to update the the user credentials via docker using var.env.

**Comment by GoebelL** [comment]
Check if it's possible to update the the user credentials via docker using var.env.

**Comment by kowalczyka** [comment]
As for now changing shell adapter related settings is possible with updating following values in var.env file:

CONTROLLER_ORG_ID
CONTROLLER_USER_KEY
CONTROLLER_USER_NAME
CONTROLLER_USER_PASS

and then running the init-db container with: 
`docker-compose -f docker-compose-initdb.yml  up oscm-initdb-controller-shell`

After this restarting oscm-app container is needed.

**Comment by GoebelL** [comment]
Described in the  [Shell Integration Guide](https://github.com/servicecatalog/documentation/blob/master/Development/oscm-app-shell/doc/en/ShellIntegration.pdf), chapter 3.2 "Updating Service Controller Settings in the Database".
