### ISSUE TITLE
Changes on expired subscription shoul be disabled

### ISSUE THREAD

**Issue by cklitscher** [servicecatalog/oscm-app-shell#67]
**Version Info**
the version of your demo system, 8th of May 2019

**Describe the bug**
If I try to modify the configuration of a subscribed service which has already expired, there is no warning, nothing is disabled on the UI and the status of the service shows still ready.

It seem like everything is ok until I press the SAVE button, then I get an error message telling me that teh service has been deactivated due to expiration.

**How to Reproduce**
1. Go to 'account/subscriptions/edit service/configuration'
2. Perform same changes
3. Scroll down to 'SAVE button'
4. See error (subscription should be expired!)

**Observed behavior**
A clear description of what was observed to happen.

**Expected behavior**
It would be better to prevent users from doing useless things like modifying a deactivated service. The status should be adjusted accordingly.

**Screenshots**
If applicable, screenshots to help explain your problem.

**Additional context**
Any other context about the problem here.

**Comment by GoebelL** [comment]
Hi @cklitscher 

I fully agree. Actually, there is an expiration handler that is invoked by a timer and that is supposed to clean up those expired subscriptions. 
According the design, the subscription is expected to be removed from the marketplace. On event of expiration, an email should be sent out to the customers with respective termination notice. For technology managers the expired subscriptions are still accessible in the administration portal. The experation details are also shown there.  
Well, probaly this handler has has failed at some point. We will check this deeper and find if this can be fixed quickly.

**Comment by cworf91** [comment]
Hello @cklitscher 

Unfortunately, we can not reconstruct the error you described. Is it possible that you send us more information?
In our case, OSCM do what is your expected behavior (see the screenshot). 
![subscription](https://user-images.githubusercontent.com/44837963/57625953-2bfba600-7595-11e9-9844-99907dd4d704.PNG)
![Configuration](https://user-images.githubusercontent.com/44837963/57625955-2bfba600-7595-11e9-9eed-bbe347ffe57d.PNG)

**Comment by GoebelL** [comment]
@cklitscher 
Thanks for your feedback. After revisiting your issue description I came to wonder if this really was an expiration use case you have digged in here. As long as the subscription is editable and in ready state, it seems to me that it hasn't expired. Are you sure the subscription should be in such state? Did you specify a number for "Number of days after which the subsription will be deactivated"? Please also note that this platform parameter is available only for services with access type 'login'. 

Does the issue still persist?

**Comment by cklitscher** [comment]
Dear Lorenz,

I did enter a value of 1 day into „Number of days…” field, and the problem arrised after a period of more than 24 hours. But I will check again when I will work with OSCM next time, I will keep you updated…

Best Regards,
Christian
