### ISSUE TITLE
Null Pointer Exception on  Gathering usage data for instance

### ISSUE THREAD

**Issue by elfriedegoetz** [servicecatalog/oscm-app-shell#71]
**Version Info**
PRIVATE-BUILD-ON-18c04074cb562019/06/18

 2019-06-26 01:57:19,816 [EjbTimerPool - 2] - INFO  - Gathering usage data for instance [b363c627-3853-4222-86e9-8e80ea92cd05] started
  20043 2019-06-26 01:57:22,319 [EjbTimerPool - 2] - ERROR - Failed to retrieve usage data for instance [b363c627-3853-4222-86e9-8e80ea92cd05]
  20044 java.lang.NullPointerException
  20045         at org.oscm.app.shell.business.usagedata.UsageHandler.registerUsageEvents(UsageHandler.java:49)
  20046         at org.oscm.app.shell.ShellController.gatherUsageData(ShellController.java:391)
  20047         at sun.reflect.GeneratedMethodAccessor174.invoke(Unknown Source)
  20048         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  20049         at java.lang.reflect.Method.invoke(Method.java:498)
  20050         at org.apache.openejb.core.interceptor.ReflectionInvocationContext$Invocation.invoke(ReflectionInvocationContext.java:205)
  20051         at org.apache.openejb.core.interceptor.ReflectionInvocationContext.proceed(ReflectionInvocationContext.java:186)

**Comment by GoebelL** [comment]
@elfriedegoetz 
This issue indicates that your usage data script does not return any usage data. The section usageData is missing in the JSON response. I have fixed the handler NPE for this case. But nevertheless, it will not work if the respective script is invalid. 
Please check if the script you have configured with the service parameter ```USAGEDATA_SCRIPT``` is the right one and that returns a vaild usage data response.
